env:
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules: {
  no-extra-semi: "warn",
  semi: "warn",
  no-var: "error",
  prefer-arrow-callback: "warn",
  space-before-function-paren: "warn",
  keyword-spacing: "warn",
  space-before-blocks: "error",
}
